version: "3.8"
services:
  app:
    build:
      args:
        user: sammy #example user
        uid: 1000
        app_debug: ${APP_DEBUG}
      context: ./
      dockerfile: docker/Dockerfile
    image: pet
    container_name: pet-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      dockernet:
        ipv4_address: 192.168.10.2

  petdb:
    image: mysql:8.0
    container_name: petdb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/logs:/var/log/mysql
    networks:
      dockernet:
        ipv4_address: 192.168.10.3

  nginx:
    image: nginx:alpine
    container_name: pet-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      dockernet:
        ipv4_address: 192.168.10.4

  pet_phpmyadmin: # use user: root, pass: sapo to login when you go localhost:8010 or if you open the fixed ip: 192.168.0.7 (below)
    image: phpmyadmin/phpmyadmin
    container_name: 'pet_phpmyadmin'
    restart: unless-stopped
    links:
      - petdb
    depends_on:
      - petdb
    ports:
      - "8081:80"
    environment:
      PMA_HOST: petdb
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    networks:
      dockernet:
        ipv4_address: 192.168.10.5

networks:
  dockernet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24


